### ISSUE TITLE
Make a link from main menu page to Project profile page

### ISSUE THREAD

**Issue by panpan2557** [SSD2015/Team2Big2Slim#11]
Also make it interact when touched.

**Comment by Sompatbu** [comment]
Some part of prototype main menu page created by @momogame also include Option button and Project Banner

**Comment by Sompatbu** [comment]
Change issue name from "Create Option button and Project banner" into "Make a link from main menu page to Project profile page" due to recent working focus on linking between two pages.

**Comment by Sompatbu** [comment]
Linking page is done. There is problem found that linking page syntax is different depend on that the page that is the link target is on the same site or different site.

**Comment by panpan2557** [comment]
We just link it with only 1 project profile page which means if you click on any project banners, it will navigate you to the same project profile page.
