### ISSUE TITLE
Create prototype Project profile page

### ISSUE THREAD

**Issue by panpan2557** [SSD2015/Team2Big2Slim#13]
For showing when project banner is touched.

**Comment by Nathakorn** [comment]
Have some labels.

**Comment by Nathakorn** [comment]
#Example
Pic_1
![screen shot 2558-03-02 at 10 53 43 pm](https://cloud.githubusercontent.com/assets/6860589/6444282/31c68358-c12f-11e4-94bd-1c0657292f65.png)

**Comment by Sompatbu** [comment]
We have done for the prototype page. Any improvement will be updated later
