### ISSUE TITLE
A score can save to database

### ISSUE THREAD

**Issue by panpan2557** [SSD2015/Team2Big2Slim#17]

**Comment by panpan2557** [comment]
A score can be saved and updated to database now. But, we fix the group that will be updated to be only ID: 1. 

Because of this bug in issue Make a choice submittable#16.

> It can be submitted but we fix the group with ID: 1 only.
> Because, we found a bug. We try to get and write the value into the element in vote.scala.html but, we can't pass the id of checked element in the list to vote method. 
> This is why we fix it to be "1".

**Comment by NutKaewnak** [comment]
An error occurred when merge code with other teammate. Coursing that it will only work on  my computer.
