### ISSUE TITLE
Test with real project code

### ISSUE THREAD

**Issue by panpan2557** [SSD2015/Team2Big2Slim#5]
Test with the real thing.

**Comment by mapfap** [comment]
I don't understand.
What is tested?
What is 'real thing'?

**Comment by panpan2557** [comment]
We intend to push easy code likes print helloWorld first then follow with the real project code.

**Comment by NutKaewnak** [comment]
Tested doesn't work. Causing by incomplete merge branches.
I will add more issue soon.
