### ISSUE TITLE
Display rating result

### ISSUE THREAD

**Issue by panpan2557** [SSD2015/Team2Big2Slim#54]

**Comment by panpan2557** [comment]
At the moment, it can only be used by admin account.
We haven't done it for the voters.

**Comment by momogame** [comment]
![rateresult](https://cloud.githubusercontent.com/assets/6860907/7271844/8dcdb244-e910-11e4-8783-2688dc7ec400.jpg)

Now rate result page can show each team with each criteria with a total rate and the average

This page can only be access by Admin
