### ISSUE TITLE
Learn to use Play framework

### ISSUE THREAD

**Issue by panpan2557** [SSD2015/Team2Big2Slim#7]
From a tutorial and try to create vote application

**Comment by Sompatbu** [comment]
Learning from Mr.Sarun guide(Introduction to Play Framework)
-   Create Project
-   Edit Routing, Controllers, Views
-   Be able to send variables from controller to view
-   Using some Scala templates

**Comment by Sompatbu** [comment]
Problem found
-   Play framework have different version on different Operating System using for development. Cause non matching syntax.
-   Need to learn HTML language for developing Play framework. This is still In progress

**Comment by NutKaewnak** [comment]
Problem found
- Framework default database need to evolve every time to run system.
  - to solve add line "applyEvolutions.default=true" with out double quote in file application.conf. Meanwhile default stand for database name

**Comment by Sompatbu** [comment]
We have learn basic Play framework so far. But we still in learning for new command and method to do with our work. So close this Issue isn't mean we stop learning them.
